### DISCUSSION TITLE
Stub file not getting included when using `--manifest` flag or building wheels

### DISCUSSION THREAD

**Discussion by bkolligs** [PyO3/maturin#1516] [General]
I am trying to deploy a wheel of a Python package, and the stub file I have in the root of my package is not getting copied to the produced wheel when I use the `--manifest` flag with `maturin develop`. Here's an example: 
I have the following directory structure for the package `maturin_manifest`: 
![image](https://user-images.githubusercontent.com/29968424/222935336-45e98cbb-955a-4c4f-b7ee-66af5044138c.png)
With the following `pyproject.toml`:
```toml
[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "maturin-manifest"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


[tool.maturin]
features = ["pyo3/extension-module"]
manifest-path = "rust/Cargo.toml"

```
When I perform the command `maturin develop -m rust/Cargo.toml` the stub file is not detected: 
```bash
🔗 Found pyo3 bindings
🐍 Found CPython 3.9 at ~/venvs/rust39/bin/python
📡 Using build options features from pyproject.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
📦 Built wheel for CPython 3.9 to /tmp/.tmpTQaQI7/maturin_manifest-0.1.0-cp39-cp39-linux_x86_64.whl
🛠 Installed maturin-manifest-0.1.0
```
But it is when I perform `maturin develop` inside the `rust` directory it does work. 
Additionally, when I try and simulate building this package from another, say as a dependency in `setup.cfg` with `pip install .`, the same thing occurs, and the stub file does not exist in the library directory.
```bash
$ ls venvs/rust39/lib/python3.9/site-packages/maturin_manifest
__init__.py
maturin_manifest.cpython-39-x86_64-linux-gnu.so
__pycache__
```
