### DISCUSSION TITLE
How do I build from the Docker image?

### DISCUSSION THREAD

**Discussion by lewisjr** [PyO3/maturin#1795] [Q&A] [answered]
Hi guys,

So I build using maturin dev -r on my local machine and the process was pretty seamless. However, when I needed the wheel to go on my server, it failed to install the wheel. So after trying to recreate it locally using the build command `sudo docker run --rm -v $(pwd):/io ghcr.io/pyo3/maturin build --release` and then `pip install <wheel>` I keep getting the following error:

```sh
ERROR: test-0.4.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

Where am I going wrong? I have scoured the discussions and issues but can't seem to find something similar my current issue. Here are my specs:

**rustup show**

```sh
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/devs/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.72.0 (5680fa18f 2023-08-23)
```

**ubuntu version:** Ubuntu 20.04.6 LTS
**docker version:** 24.0.6, build ed223bc
**python version:** 3.8.10
**cargo version:** 1.72.0
**maturin version:** 1.2.3

<details>
<summary><strong>Cargo.toml</strong></summary>

```toml
[package]
name = "test"
version = "0.4.0"
edition = "2021"

[lib]
name = "test"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
```
</details>

<details>
<summary><strong>pyproject.toml</strong></summary>

```toml
[build-system]
requires = ["maturin>=1.2.3"]
build-backend = "maturin"

[project]
name = "test"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


[tool.maturin]
features = ["pyo3/extension-module"]
```
</details>
