### DISCUSSION TITLE
My modules stub file is not included in the wheel

### DISCUSSION THREAD

**Discussion by gaborbernat** [PyO3/maturin#2079] [Q&A] [answered]
https://github.com/gaborbernat/pyproject-fmt-rust/blob/main/src/pyproject_fmt/_lib.pyi

```toml
[tool.maturin]
bindings = "pyo3"
manifest-path = "Cargo.toml"
module-name = "pyproject_fmt._lib"
python-source = "src"
strip = true
include = [
  "rust-toolchain.toml",
]
```
Any idea why?
