### DISCUSSION TITLE
Error checking for manylinux/musllinux compliance

### DISCUSSION THREAD

**Discussion by cyrus937** [PyO3/maturin#2216] [Q&A]
Hello,
I hope you're well.
I currently have a problem when I try to deploy my project. Indeed, I had to do a project in which I use pyo3 and maturin, I've been trying for some time to deploy my python project using a gitlab pipeline, but I get this error when I run the command `maturin build --release`:
```bash
Finished `release` profile [optimized] target(s) in 2m 34s
💥 maturin failed
  Caused by: Error checking for manylinux/musllinux compliance
  Caused by: Your library links libpython (libpython3.11.so.1.0), which libraries must not do. Have you forgotten to activate the extension-module feature?
```

My `Cargo.toml` file is as follows:
```toml
[package]
name = "py_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "py_project"
# "cdylib" is necessary to produce a shared library for Python to import from.
#
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use string_sum;` unless the "rlib" or "lib" crate type is also included, e.g.:
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.33", features = ["full"] }
futures = "0.3.29"
pyo3 = {version = "0.20.0", features = ["extension-module"]}
pyo3-asyncio = { version = "0.20", features = ["attributes", "tokio-runtime"] }
async-std = "1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand="0.8.5"
csv = "1.1.6"
env_logger = "0.11.5"
murmur3 = "0.5.2"
```

Please, can you help me
