### DISCUSSION TITLE
build in `dev` profile by default, `release` if requested

### DISCUSSION THREAD

**Discussion by nschloe** [PyO3/maturin#2567] [Q&A]
I'd like my project to build in the `dev` profile by default. To this end, I added
```toml
[tool.maturin]
profile = "dev"
```
to my `pyproject.toml`. However, I can't seem to override this. `maturin build --release` still builds in `dev` mode.

Any hints?
