### DISCUSSION TITLE
Why is maturin ignoring my `compatibility` config when called with `uv build --wheel` ?

### DISCUSSION THREAD

**Discussion by dedebenui** [PyO3/maturin#2600] [Q&A]
I'm using uv and maturin for a project, and I want to use uv to build wheels. In my `pyproject.toml`, I wrote:

```toml
[tool.maturin]
python-source = "python"
module-name = "propoptics._lib_propoptics"
features = ["pyo3/extension-module"]
compatibility = "manylinux_2_34"
```

but maturing still gets called with `--compatibility off` when calling `uv build --wheel`. Why is Maturing ignoring my config? According to [this](https://github.com/astral-sh/uv/issues/11245), it's not done on `uv`'s side. It's not a big deal since `maturin build` works fine, but I was just wondering
