### DISCUSSION TITLE
cibuildwheel fails on ubuntu aarch64

### DISCUSSION THREAD

**Discussion by RobertCraigie** [PyO3/maturin#743] [Q&A]
https://github.com/RobertCraigie/prisma-client-py/runs/4497941477?check_suite_focus=true

Is this architecture supported? Am I doing something wrong?

Relevant part of the actions workflow:
```yml
jobs:
  build-query-engine:
    name: Build Query Engine py3${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["6", "7", "8", "9", "10"]
        os: [ubuntu-20.04, windows-2019, macos-10.15]
    env:
      # TODO: run tests on the built wheels
      CIBW_BUILD: "cp3${{ matrix.python-version }}-*"
      CIBW_BUILD_VERBOSITY: 1
      CIBW_BEFORE_ALL_LINUX: "curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y && yum install -y openssl-devel"
      CIBW_BEFORE_BUILD_LINUX: "pip3 install --upgrade keyrings.alt"
      CIBW_ARCHS_LINUX: "auto aarch64"
      CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
      CIBW_SKIP: "cp27-* cp34-* cp35-* pp* *-win32"

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup env
        run: |
          python -m pip install --upgrade wheel setuptools maturin

      - if: runner.os == 'Linux'
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Install cibuildwheel
        run: |
          python -m pip install -U cibuildwheel==2.3.0
      - name: Build wheels
        working-directory: src/query-engine
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./src/query-engine/wheelhouse/*.whl
```

`pyproject.toml`
```toml
[tool.black]
skip-string-normalization = true

# TODO: metadata
# https://maturin.rs/metadata.html

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
```

`cargo.toml`
```toml
[package]
name = "prisma-py-query-engine"
version = "0.0.1"
edition = "2018"
authors = ["Robert Craigie <robert@craigie.dev>"]

[lib]
name = "_prisma_query_engine"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
query-core = { git = "https://github.com/prisma/prisma-engines", rev = "33838b0" }
pyo3-asyncio = { git = "https://github.com/awestlake87/pyo3-asyncio", features = ["attributes", "tokio-runtime"] }
request-handlers = { git = "https://github.com/prisma/prisma-engines", rev = "33838b0" }
query-connector = { git = "https://github.com/prisma/prisma-engines", rev = "33838b0" }
user-facing-errors = { git = "https://github.com/prisma/prisma-engines", rev = "33838b0" }
datamodel = { git = "https://github.com/prisma/prisma-engines", rev = "33838b0" }
sql-connector = { git = "https://github.com/prisma/prisma-engines", package = "sql-query-connector", rev = "33838b0" }
prisma-models = { git = "https://github.com/prisma/prisma-engines", rev = "33838b0"  }
datamodel-connector = { git = "https://github.com/prisma/prisma-engines", rev = "33838b0" }
url = "2"
serde = "1"
connection-string = "0.1"
tokio = { version = "1", features = ["sync"] }
serde_json = { version = "1", features = ["preserve_order", "float_roundtrip"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
tracing-opentelemetry = "0.11"
thiserror = "1.0"
opentelemetry = "0.12"
opentelemetry-otlp = { version = "0.5", features = ["tls", "tls-roots"] }
crossbeam-channel = "0.5.1"

[dependencies.pyo3]
version = "0.14.5"
features = ["extension-module"]
```
