### DISCUSSION TITLE
Markdown readme errors

### DISCUSSION THREAD

**Discussion by NiceneNerd** [PyO3/maturin#916] [Q&A]
No matter what I try with my maturin project, having a readme in Markdown will not work properly. If I try to to publish to PyPI it complains that it is not valid ReStructured Text, and if I use `twine check` on built wheels it complains about description syntax and missing content type.

The following pertinent lines are already in `pyproject.toml`, and I still have an old `setup.py` that correctly specifies this data:
```toml
[project]
# ...
readme = { content-type = "text/markdown", file = "docs/README.md" }
# ...
[project.metadata.maturin]
description-content-type = "text/markdown"
```

I've been searching diligently for anything else to try, and have tried a number of apparently related or similar options, but have found nothing that seems to do anything.
