### ISSUE TITLE
MIPS architectures support

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#1022]
I saw this PR in home-assistant: https://github.com/home-assistant/core/pull/75318 that complains about lacking of MIPS architectures support in maturin.

- [x] `ring` dependency is only used for the upload feature, it can be disabled for unsupported architectures
- [x] `goblin` throws `type is too big` error on MIPS: https://github.com/m4b/goblin/issues/274, ignored the error since it's only used for emitting a warning
- [x] mips64el: #1023 
- [x] mipsel: #1024
- [ ] mips? No easy way to test this, I don't think we should support it because Debian already dropped support. https://www.debian.org/ports/mips/, https://www.phoronix.com/news/Debian-Drops-Old-32-Bit-MIPS

@Arnie97 I assume you have MIPS devices that can do testing? Would you like to help us to add MIPS support?

**Comment by messense** [comment]
FYI, we already added 64-bit RISC-V in https://github.com/PyO3/maturin/pull/1001.

**Comment by Arnie97** [comment]
@messense Great job :tada:

I've tested the latest beta verson on mips(eb), mipsel and 64-bit RISC-V this weekend, and everything worked smoothly. However I did not test the "upload to PyPI" command yet; I did not have a actual maturin project, so I'm trying to figure out how to upload to https://test.pypi.org/.

```yaml
hass@K3C ~ $ pip3 --version
pip 22.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)

hass@K3C ~ $ uname -m
mips

hass@K3C ~ $ head -15 /proc/cpuinfo
system type             : GRX500 rev 1.2
machine                 : EASY350 ANYWAN (GRX350) Router model
processor               : 0
cpu model               : MIPS interAptiv V2.0
cpu MHz                 : 600.000
BogoMIPS                : 387.07
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : dsp mt eva
shadow register sets    : 1
kscratch registers      : 0


hass@K3C ~ $ pip install --user maturin==0.13.2-beta.2
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Collecting maturin==0.13.2-beta.2
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/6d/cf/035fe84d715a6f2af4561ca1f0eb27ba6d4e4745ee47db1063ecb9f03e80/maturin-0.13.2b2.tar.gz (143 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tomli>=1.1.0 in /usr/lib/python3.10/site-packages (from maturin==0.13.2-beta.2) (2.0.1)
Building wheels for collected packages: maturin
  Building wheel for maturin (pyproject.toml) ... done
  Created wheel for maturin: filename=maturin-0.13.2b2-cp310-cp310-linux_mips.whl size=8559225 sha256=72ba1885bda6129f9e31e4d00a8d2c65328189ec0badcde5fe6c1a6411470c8b
  Stored in directory: /home/hass/.cache/pip/wheels/f9/00/b0/3ed5070408f9c155a7afe4d7bd39cc6f9cfe2d895f01f0ed2e
Successfully built maturin
Installing collected packages: maturin
Successfully installed maturin-0.13.2b2
```
