### ISSUE TITLE
Maturin crashes, crash report included

### ISSUE THREAD

**Issue by dswalter** [PyO3/maturin#1061]
### Bug Description

I tried to run `maturin develop` on a project a team-mate build, and maturin crashed before doing anything

the output from maturin's bug report is reproduced here.

```bash
❯ maturin build
🐍 Found CPython 3.9 at /Users/daniel.walter/repos/plt_bon/validate/mat2/bin/python3
Well, this is embarrassing.

maturin had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/var/folders/g_/zkzjjftj0x1c4_t8v9vzpr31xbyby6/T/report-15b44d0f-5bff-44bc-a59f-f2841f92211f.toml". Submit an issue or email with the subject of "maturin Crash Report" and include the report as an attachment.

- Homepage: https://github.com/pyo3/maturin
- Authors: konstin <konstin@mailbox.org>, messense <messense@icloud.com>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
```

That message is reproduced below:
```
name = 'maturin'
operating_system = 'unix:OSX'
crate_version = '0.13.2'
explanation = '''
Panic occurred in file 'src/build_context.rs' at line 683
'''
cause = 'called `Option::unwrap()` on a `None` value'
method = 'Panic'
backtrace = '''

   0: 0x10df5d243 - core::panicking::panic_fmt::h3d9f795ee387ef8d
   1: 0x10df5d127 - core::panicking::panic::h02eb82771823ab30
   2: 0x10d758d26 - maturin::build_context::BuildContext::build_bin_wheel::hf7bdbd7df780bf4d
   3: 0x10d7590ab - maturin::build_context::BuildContext::build_bin_wheels::h85bc5657034c6875
   4: 0x10d74f624 - maturin::build_context::BuildContext::build_wheels::h5ffda8ee100be5de
   5: 0x10d63dd8a - maturin::develop::develop::h3966b54ca2b2b033
   6: 0x10d53868a - maturin::run::hd32db0e39ad64948
   7: 0x10d53c349 - maturin::main::hf5e2de284e82d5b3
   8: 0x10d5451f6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h366cede250136f46
   9: 0x10d54568c - std::rt::lang_start::{{closure}}::hb25d0d5322258eb9
  10: 0x10dee6a2e - std::rt::lang_start_internal::h3fd5cff071397f19
  11: 0x10d542ad9 - _main'''
```

### Your Python version (`python -V`)

Python 3.9.6

### Your pip version (`pip -V`)

21.1.3

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

I ran `maturin build` in a fresh venv, as was described in the README.md for maturin.

Both `maturin build` and `maturin develop`  show the same message.

**Comment by messense** [comment]
Thanks for the report, the offending line is https://github.com/PyO3/maturin/blob/c1e93e0aca48b6a1fde34801ef2ce013e63ef66c/src/build_context.rs#L683

It shouldn't have panicked, can you share the code, if not do you have a minimal reproduction?

**Comment by messense** [comment]
You were saying you're using `pyo3` bindings, but the offending code is for `bin` bindings though.

**Comment by dswalter** [comment]
My colleague who built it (and for whom it did work) is on Ubuntu 20.04. My machine is a mac.

Here is a rough approximation of the code.

```rust
#![allow(unused)]

use pyo3::prelude::*;
use validate::serde_json;
pub use validate::{JsonBlob, Annotations, Parsed};

#[pyclass]
pub struct Validation {
    annotations: Vec<String>,
    parsed: validate::JsonBlob,
    meta: validate::ParsedMeta,
}

#[pymethods]
impl Validation {
    #[getter]
    fn annotations(&self) -> Vec<String> {
        self.annotations.clone()
    }

    #[getter]
    fn in_order(&self) -> bool {
        self.meta.in_order
    }

    #[getter]
    fn num_unknown_fields(&self) -> usize {
        self.meta.num_unknown_fields
    }

    #[getter]
    fn num_errors(&self) -> usize {
        self.meta.num_errors
    }

    #[getter]
    fn first_unordered_key(&self) -> Option<String> {
        self.meta.first_unordered_key.map(|(key, _)| key.to_owned())
    }

    #[getter]
    fn first_unordered_key_index(&self) -> Option<usize> {
        self.meta.first_unordered_key.map(|(_, idx)| idx)
    }
}

/// Formats the sum of two numbers as string.
#[pyfunction]
fn parse_and_validate(json: String) -> PyResult<Validation> {
    let value = serde_json::from_str::<serde_json::Value>(&json).unwrap();
    let (annotations, parsed, meta) = validate::parse_and_validate_with_meta(&value);
    let annotations = annotations.into_iter().map(|label| label.to_string()).collect();
    Ok(Validation {
        annotations,
        parsed,
        meta,
    })
}

/// A Python module implemented in Rust.
#[pymodule]
fn validate_py(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(parse_and_validate, m)?)?;
    Ok(())
}
```

**Comment by messense** [comment]
What about the project layout? Contents of pyproject.toml and Cargo.toml?

**Comment by dswalter** [comment]
Cargo.toml
```toml
[package]
name = "project_py"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "project_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
project = { path = "../project", features = ["foo_feature"] }
anyhow = "1"
```

pyproject.toml
```toml
[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "project_py"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
```
