### ISSUE TITLE
`maturin init` creates `Cargo.toml` incorrectly

### ISSUE THREAD

**Issue by OWissett** [PyO3/maturin#1120]
### Bug Description

When running `maturin init`, the `Cargo.toml` is missing the `[lib]` tag, leading to `maturin build` (and all other commands) to fail.

Example output:
```toml
[package]
name = "getting_started"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html[lib]
name = "getting_started"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
```
Expected:

```toml
[package]
name = "getting_started"
version = "0.1.0"
edition = "2021"

[lib]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html[lib]
name = "getting_started"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
```

OS:  MacOS, Monterey 12.0.1 
Arch: Arm64, M1 2020

### Your Python version (`python -V`)

3.10.6

### Your pip version (`pip -V`)

22.2.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. create virtualenv: `python3.10 -m virtualenv .venv; ./.venv/bin/activate`
2. install maturin: `pip install maturin`
3. create project: `maturin init`
4. done.
