### ISSUE TITLE
`[lib]` section in `Cargo.toml` on comment line

### ISSUE THREAD

**Issue by bicarlsen** [PyO3/maturin#1126]
### Bug Description

When initiating a new project using `maturin init` the `Cargo.toml` file is initialized as
```toml
[package]
name = "my_package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html[lib]
name = "my_package"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
```
where the `[lib]` section header was included in the comment line. The correct file should be
```toml
[package]
name = "my_package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "my_package"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
```

### Your Python version (`python -V`)

3.9.12

### Your pip version (`pip -V`)

22.2.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Create folder called `my_package`
2. Initialize a virtualenv
3. run `maturin init`
4. Select `pyo3` bindings
