### ISSUE TITLE
GitLab pipeline support in `maturin generate-ci`

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#1507]
I don't use GitLab so I'm not going to work on this anytime soon, help appreciated!

**Comment by Owen-CH-Leung** [comment]
I'm trying to create PR for this issue and would love to get some thoughts about the implementation. 

Gitlab CI essentially is different from github actions and thus I think not all logics built in the `generate_github` API [here](https://github.com/PyO3/maturin/blob/main/src/ci.rs#L137) can be applied to a new API like `generate_gitlab`. So Does it make sense to start the CI pipeline for gitlab with `image: ghcr.io/pyo3/maturin:latest` ? Or we should start the pipeline with a base image like `alpine` and start everything from scratch ? 

I'd imagine that the generated CI pipeline for gitlab would look sth like below: 

```
linux_build:
  stage: build
  image: ghcr.io/pyo3/maturin:latest
  tags:
    - linux / window 
  script:
    parallel:
      matrix:
        - TARGET: ["x86_64", "x86", "aarch64", "armv7", "s390x", "ppc64le"]
    - >
      maturin build --release --out dist --find-interpreter --target $TARGET
      [rest of the script to follow]
```

The problem with starting with `image: ghcr.io/pyo3/maturin:latest` though, is that some logic built in for the Emscripten platfor may not be applicable. What do you think ?

**Comment by messense** [comment]
We can start from scratch, but we should only use `alpine` for musl targets, for gnu targets you'd need to use some manylinux compatible docker images.

**Comment by mpizenberg** [comment]
Hi, I'm quite interested in this too as I will try to set up a gitlab pipeline for my project. What's the best practice currently? Is there documentation somewhere already?

**Comment by messense** [comment]
Sorry I don't know much about gitlab pipeline, we can come up with a basic one first and optimize later.

**Comment by shehab-as** [comment]
Hi there, @mpizenberg are you still working on this?

I've already setup a gitlab pipeline for my project using maturin and I'm interested to add a minimal version for review.

**Comment by messense** [comment]
@shehab-as Feel free to open a PR.

**Comment by osintalex** [comment]
@shehab-as could you share your gitlab yaml? Happy to collaborate on a PR. I have a rough untested draft of how I'd lay this out to achieve parallelization on different platforms and caching.

I think if we can pin down a valid gitlab yaml that covers all the edge cases that's the best starting point - then we can figure out how to build it dynamically in the `generate-ci` command.

```yaml
default:
    before_script:
        - poetry config virtualenvs.in-project true
    cache:
        paths:
            - .venv
            - .cargo/bin
            - .cargo/registry/index
            - .cargo/registry/cache
            - target/debug/deps
            - target/debug/build
 
variables:
    CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

stages:          
  - build
  - test
  - publish

build-general:
  needs: []
  stage: build
  image: ghcr.io/pyo3/maturin:latest
  environment:
    name: $TARGET
  tags:
    - $TARGET
  parallel:
    matrix:
      - TARGET: ["x86_64", "x86", "aarch64", "armv7", "s390x", "ppc64le"]
  script:
    - maturin build --release --out dist --find-interpreter --target $TARGET
  artifacts:
    when: on_success
    paths:
        - dist/

build-musl:
  needs: []
  stage: build
  image: alpine
  script:
    - maturin build --release --out dist --find-interpreter --target 'musl value goes here'
  artifacts:
    when: on_success
    paths:
        - dist/

test: 
  needs: [build-general, build-musl]
  stage: test
  script:
    - maturin develop
    - pip install pytest
    - pytest
  tags:
    - $IMAGE
  parallel:
    matrix:
      - IMAGE: ["linux", "windows", "macos"]
  image: $IMAGE

publish: 
  needs: [build-general, build-musl, test]
  stage: test
  image: ghcr.io/pyo3/maturin:latest
  dependencies: [build-general, build-musl]
  script:
    - maturin publish --non-interactive --skip-existing

```

**Comment by messense** [comment]
@osintalex Feel free to take it over if there is no response/PR from @shehab-as for several weeks.

**Comment by shehab-as** [comment]
@osintalex hey, thanks for sharing. Here's a refined (and untested) version of my gitlab-ci yaml. 
It is similar to what you have, with addition to multi python version support and opinionated release rules. 

Happy to collaborate on a PR. I've already made some progress in my fork, I can add you to the PR once I push latest changes in my branch, and from there we can discuss a "comprehensive" version of gitlab-ci per your proposal.

```
default:
  interruptible: true

variables:
    CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

stages: 
  - build
  - test
  - release

build-linux:
  stage: build
  image: ghcr.io/pyo3/maturin:latest
  parallel:
    matrix:
      - TARGET:
        - x86_64-unknown-linux-gnu
        - x86_64-unknown-linux-musl
        - aarch64-unknown-linux-gnu
        - aarch64-unknown-linux-musl
  script:
    - maturin build -i python3.8 -i python3.9 -i python3.10 -i python3.11 -i python 3.12 --release --target $TARGET
  artifacts:
    paths:
      - target/wheels/*.whl

test-linux:
  stage: test
  image: ghcr.io/pyo3/maturin:latest
  needs: ["build-linux"]
  before_script:
    - maturin develop
    - pip install pytest
  script:
    - pytest

publish:
  stage: release
  image: ghcr.io/pyo3/maturin:latest
  needs: ["build-linux", "test-linux"]
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true
  script:
    - maturin publish --non-interactive --skip-existing
```
