### ISSUE TITLE
No way to give Rust and Python project a different name.

### ISSUE THREAD

**Issue by flying-sheep** [PyO3/maturin#1520]
### Bug Description

Apologies if there is a way, I searched for quite a while and didn’t find it.

I want to create a crate that is also deployed to PyPI.

On crates.io, it has the name `xdot` (already published), on PyPI it’s supposed to have the name `xdot-rs` (and be importable as `import xdot_rs`)

This doesn’t seem to be possible as `[tool.maturin]` doesn’t seem to have an option for this, and when just using the intended names, maturin complains:

> ⚠️  Warning: Couldn't find the symbol `PyInit_xdot` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `xdot` as module name

This advice isn’t actionable, since I can neither use `xdot` as Python package name (it already exists) nor am I able (or want to) rename the Rust crate to `xdot-rs`.

### Your maturin version (`maturin --version`)

0.14.15

### Your Python version (`python -V`)

3.10.9

### Your pip version (`pip -V`)

23.0.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### Steps to Reproduce

`Cargo.toml`
```toml
[package]
name = 'xdot'
...

[dependencies]
...
pyo3 = { version = '0.18.1', optional = true, features = ['extension-module']}
```

`pyproject.toml`
```toml
[build-system]
...
[project]
name = 'xdot-rs'
...
[tool.maturin]
features = ['pyo3']
```

`src/lib.rs`
```rust
...

#[cfg(feature = "pyo3")]
#[pyo3::pymodule]
#[pyo3(name = "xdot_rs")]
pub fn pymodule(py: pyo3::Python, m: &pyo3::types::PyModule) -> pyo3::PyResult<()> {
    ...
    Ok(())
}
```

**Comment by messense** [comment]
Have you tried

```toml
[package.metadata.maturin]
name = "xdot_rs"
```

?

The module name has to be aligned with the dylib name which defaults to `package.name` in Cargo.toml and can be override with `package.metadata.maturin.name`.
