### ISSUE TITLE
Consider adding `lto = "thin"` to generated Cargo.toml's release profile

### ISSUE THREAD

**Issue by itamarst** [PyO3/maturin#1529]
In my experience, thin LTO always give a small but noticeable performance boost to PyO3 Python extensions. As such, it would be nice if maturin just added it; one less thing for users to know they have to do.

```toml
[profile.release]
lto = "thin"
```
