### ISSUE TITLE
[bug] Maturin's wheel contains two copies of LICENSE when using license-file in workspace crate Cargo.toml

### ISSUE THREAD

**Issue by HerringtonDarkholme** [PyO3/maturin#2066]
### Bug Description

I'm using carge workspace to publish my project. 

The main CLI project uses `license-file` to include a license file for downstream packager. https://github.com/ast-grep/ast-grep/pull/473

However, this makes maturin includes two copies of LICENSE. https://github.com/ast-grep/ast-grep/issues/766

<img width="915" alt="image" src="https://github.com/PyO3/maturin/assets/2883231/1aeab91d-0788-4621-8d66-9277079b0b8d">

### Your maturin version (`maturin --version`)

0.15.0

### Your Python version (`python -V`)

3.10

### Your pip version (`pip -V`)

23.3.1

### What bindings you're using

bin

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Crates.toml 
```toml
[package]
name = "ast-grep"
license-file = "../../LICENSE"
```

2. pyproject.toml in root directory
```toml
[project]
name = "ast-grep-cli"
[tool.maturin]
bindings = "bin"
manifest-path = "crates/cli/Cargo.toml"
```

3. build
```bash
maturin build
```

4.  examine the wheel
```bash
unzip -l target/wheels/ast_grep_cli.whl
```

Example repo: 

https://github.com/ast-grep/ast-grep
