### ISSUE TITLE
RECORD file is missing entries for some files

### ISSUE THREAD

**Issue by LilyFoote** [PyO3/maturin#2106]
### Bug Description

In [Kolo](https://pypi.org/project/kolo/) we include some javascript, css and image files, but these are missing from the `RECORD` file leading to warnings when installing via poetry:

```
  - Updating kolo (2.19.0 /home/lily/work/kloppindustries/kolo/python -> 2.28.0)
Warning: Validation of the RECORD file of kolo-2.28.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl failed. Please report to the maintainers of that package so they can fix their build process. Details:
In /home/lily/.cache/pypoetry/artifacts/08/e7/b2/fa79bba4ab7475b65767ca192d9e0759e65ec3bbb4c0fe33e3a28b6c53/kolo-2.28.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, kolo/web/static/.gitignore is not mentioned in RECORD
In /home/lily/.cache/pypoetry/artifacts/08/e7/b2/fa79bba4ab7475b65767ca192d9e0759e65ec3bbb4c0fe33e3a28b6c53/kolo-2.28.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, kolo/web/static/favicons/favicon-dark-16x16.png is not mentioned in RECORD
In /home/lily/.cache/pypoetry/artifacts/08/e7/b2/fa79bba4ab7475b65767ca192d9e0759e65ec3bbb4c0fe33e3a28b6c53/kolo-2.28.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, kolo/web/static/favicons/favicon-dark-32x32.png is not mentioned in RECORD
In /home/lily/.cache/pypoetry/artifacts/08/e7/b2/fa79bba4ab7475b65767ca192d9e0759e65ec3bbb4c0fe33e3a28b6c53/kolo-2.28.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, kolo/web/static/favicons/favicon-light-16x16.png is not mentioned in RECORD
In /home/lily/.cache/pypoetry/artifacts/08/e7/b2/fa79bba4ab7475b65767ca192d9e0759e65ec3bbb4c0fe33e3a28b6c53/kolo-2.28.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, kolo/web/static/favicons/favicon-light-32x32.png is not mentioned in RECORD
In /home/lily/.cache/pypoetry/artifacts/08/e7/b2/fa79bba4ab7475b65767ca192d9e0759e65ec3bbb4c0fe33e3a28b6c53/kolo-2.28.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, kolo/web/static/favicons/favicon.ico is not mentioned in RECORD
In /home/lily/.cache/pypoetry/artifacts/08/e7/b2/fa79bba4ab7475b65767ca192d9e0759e65ec3bbb4c0fe33e3a28b6c53/kolo-2.28.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, kolo/web/static/kolo-logo-full.svg is not mentioned in RECORD
In /home/lily/.cache/pypoetry/artifacts/08/e7/b2/fa79bba4ab7475b65767ca192d9e0759e65ec3bbb4c0fe33e3a28b6c53/kolo-2.28.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, kolo/web/static/main.css is not mentioned in RECORD
In /home/lily/.cache/pypoetry/artifacts/08/e7/b2/fa79bba4ab7475b65767ca192d9e0759e65ec3bbb4c0fe33e3a28b6c53/kolo-2.28.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, kolo/web/static/main.js is not mentioned in RECORD
```

### Your maturin version (`maturin --version`)

1.6.0

### Your Python version (`python -V`)

Any

### Your pip version (`pip -V`)

N/A

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. Install poetry
2. `poetry init`
3. `poetry add kolo`
4. Observe warnings

A fragment of our CI release workflow (the rest is similar):

```yaml
name: Kolo Python Release

on:
  push:
    tags: python-*

jobs:
  build_static_webapp:
    # Static files from webapp to be bundled into the Python package
    name: Build static webapp
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Build static files
        working-directory: ./vscode
        run: |
          npm ci
          npm run compile:webapp
      - run: ls python/src/kolo/web/static/
      - name: Upload Static Files
        uses: actions/upload-artifact@v4
        with:
          name: static-webapp
          path: python/src/kolo/web/static/

  build_sdist:
    name: Build source distribution
    needs: [build_static_webapp]
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - run: ls python/src/kolo/web/static/
      - name: Download Static Files
        uses: actions/download-artifact@v4
        with:
          name: static-webapp
          path: python/src/kolo/web/static/
      - run: ls python/src/kolo/web/static/

      - name: Build sdist
        working-directory: ./python
        run: pipx run build --sdist

      - run: pip install maturin
      - run: pip install kolo --find-links=./python/dist/
      - run: pip install pytest
      - name: Test sdist
        run: KOLO_PATH=$(realpath ./python) pytest ./python/tests/test_minimal.py

      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist.tar.gz
          path: python/dist/*.tar.gz

  macos:
    name: Build wheels on MacOS
    needs: [build_static_webapp]
    runs-on: macos-latest
    strategy:
      matrix:
        python-version:
          ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy-3.9", "pypy-3.10"]

    steps:
      - uses: actions/checkout@v4

      - run: ls python/src/kolo/web/static/
      - name: Download Static Files
        uses: actions/download-artifact@v4
        with:
          name: static-webapp
          path: python/src/kolo/web/static/
      - run: ls python/src/kolo/web/static/

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist
          working-directory: python

      - run: pip install kolo --find-links=./python/dist/
      - run: pip install pytest
      - name: Test wheel
        run: KOLO_PATH=$(realpath ./python) pytest ./python/tests/test_minimal.py

      - uses: actions/upload-artifact@v4
        with:
          name: dist-macos-${{ matrix.python-version }}.whl
          path: python/dist/*.whl
```
