### ISSUE TITLE
maturin build does not normalize local dependencies

### ISSUE THREAD

**Issue by etamponi** [PyO3/maturin#238]
Hi!

First of all: maturin (and the whole pyo3 project) is amazing. I got up and running in less than a day (coming from wasm-bindgen... that took way longer).

Unfortunately, the `maturin build` command does not normalize the dependencies in Cargo.toml:

```toml
[package]
name = "python_bindings"
version = "0.1.0"
authors = [
  "Emanuele Tamponi <emanuele.tamponi@gmail.com>"
]
description = "Python Bindings for a Rust Library"
repository = "https://github.com/etamponi/mock-project"
license = "AGPL-3.0-only"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust-library = { path = "../../rust", version = "1.0.0" }

[dependencies.pyo3]
version = "0.8.2"
features = ["extension-module"]
```

When I run `maturin build` and I inspect the Cargo.toml file in the source distribution, I see that it still has the relative path to `rust-library` in it, making it impossible to build.

On the other hand, `cargo package` correctly updates the `dependencies` to fetch the package from crates.io (it removes the `path`).
