### ISSUE TITLE
build matrix for wheels?

### ISSUE THREAD

**Issue by trim21** [PyO3/maturin#2411]
I'm updating ci build from opendal and we release `cp310-manylinux`,`cp311-abi3`,`cp313-cp313t-manylinux` wheels.

`cp310-manylinux` and `cp313-cp313t-manylinux` can be conbined as `build -o dist -i python3.10 -i python3.13t`, but `abi3` feature is enabled with `--features=abi3` make it must exists in a seprated command, and therefore make it build whole project twice.

Is there any possible to make then unified?

for example: 

```toml
[[tool.matruin.matrix]]
interpreter = '3.10'

[[tool.matruin.matrix]]
interpreter = '3.13t'

[[tool.matruin.matrix]]
interpreter = '3.11'
features = ['abi3']
```
