### ISSUE TITLE
Unable to import after maturin develop (or maturin build and pip install)

### ISSUE THREAD

**Issue by FrankC01** [PyO3/maturin#2651]
### Bug Description

When I do a `maturin develop` on a Rust only wrapper project (src/lib.rs) and then attempt to test with a simple python script, attempting to import the newly install library has these errors:

```shell
"pytusk_seal" is not accessedPylance
Unable to import 'pytusk_seal'Pylint[E0401:import-error](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/import-error.html)
Unused import pytusk_sealPylint[W0611:unused-import](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unused-import.html)
Import "pytusk_seal" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pylance-release/blob/main/docs/diagnostics/reportMissingImports.md)
Import "pytusk_seal" is not accessedPylance[reportUnusedImport](https://github.com/microsoft/pylance-release/blob/main/docs/diagnostics/reportUnusedImport.md)
```

### Your maturin version (`maturin --version`)

1.8.7

### Your Python version (`python -V`)

3.10.6

### Your pip version (`pip -V`)

25.0.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [x] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

Cargo.toml
```toml
[package]
name = "pytusk-seal"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pytusk_seal"
crate-type = ["cdylib"]

[dependencies]
fastcrypto = "0.1.9"

[dependencies.pyo3]
version = "0.25.0"
# "abi3-py37" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.10
features = ["abi3-py310"]
```

pyproject.toml
```toml
[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

[project]
name = "pytusk-seal"
version = "0.1.0"
readme = "README.rst"
requires-python = ">=3.10"
license = { file = "LICENSE" }
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
]
```
src/lib.rs
```rust
use pyo3::prelude::*;

/// Formats the sum of two numbers as string.
#[pyfunction]
fn sum_as_string(a: usize, b: usize) -> PyResult<String> {
    Ok((a + b).to_string())
}

In editor, (temp_test.py)
```python
#
"""."""

import pytusk_seal # Unable to import
```
/// A Python module implemented in Rust.
#[pymodule]
fn pytusk_seal(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(sum_as_string, m)?)?;
    Ok(())
}
```

maturin develop
```shell
🔗 Found pyo3 bindings with abi3 support
🐍 Not using a specific python interpreter
📡 Using build options features from pyproject.toml
   Compiling pytusk-seal v0.1.0 (/Users/fastfrank/suitters/pytusk-seal)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.13s
📦 Built wheel for abi3 Python ≥ 3.10 to /var/folders/xz/v9xrxt3d57sbw44j2trqqjp00000gn/T/.tmpCU0P9E/pytusk_seal-0.1.0-cp310-abi3-macosx_11_0_arm64.whl
✏️ Setting installed package as editable
🛠 Installed pytusk-seal-0.1.0
```
