### ISSUE TITLE
Ship both python library AND binary command line tool in wheel

### ISSUE THREAD

**Issue by PeterQLee** [PyO3/maturin#368]
I'm in a situation where I would like to build both a python library and a command line tool in a wheel for distribution. (e.g., https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html , but all the code would be in rust.)

The Cargo.toml would contain:
```toml
...
[lib]
crate-type = ["staticlib", "cdylib"]
name = "my_library"
path = "src/lib.rs"

[[bin]]
name = "my_commandline"
path= "src/cli.rs"
...
```

Is it possible to do this in maturin?

I've tried doing `maturin build -b "bin"`, which only builds the command line tool (my_commandline) and not the library.
`maturin build -b "pyo3"` likewise only builds the library (my_library) and not the command line tool.

Is it currently possible to build with both "bin" and "pyo3" bindings in a single wheel?

**Comment by konstin** [comment]
For shipping both library and binary, you'd need to build twice and ship both binaries, having two copies of each dependency in the wheel. Would it be possible to work around issue by adding a pseudo-main to the rust library and creating a small python script that  only calls the main of library?

**Comment by rmcgibbo** [comment]
Does anyhow know how to do this from the pyproject.toml, so that `pip wheel` or `pip install` builds either the po3 or the bin type of wheel, since we can't get them both into the same wheel?

**Comment by messense** [comment]
After #948 we now have the skeleton to allow shipping both lib and bin, the remaining question is how to let users to configure it. We'd still want maturin to by default only build `lib` or `bin`, build for both of them when asked to.

I'm thinking about adding the following options to `pyproject.toml` (and `Cargo.toml`):

```toml
[[tool.maturin.targets]]
name = "example"
kind = "bin"

[[tool.maturin.targets]]
name = "example"
kind = "lib"
```

Then you will get a `libexample` and `example` binary in the wheel.

I don't quite like the `targets` metadata name, easily gets confused with cargo's `--target`.

**Comment by davidhewitt** [comment]
Sounds good to me. Agreed `targets` is a little confusing, though it really is the name used by Cargo for these things: https://doc.rust-lang.org/cargo/reference/cargo-targets.html#cargo-targets

**Comment by dylanbstorey** [comment]
I like it and while `targets` might be a little confusing at first blush, it seems like a community standard and not an inordinate cognitive barrier to understand and easy to document.

**Comment by messense** [comment]
Thanks for the feedback!

While thinking more about this, there is a question on how does the existing `--bindings` option interacts with `targets`, there might be cases where the `lib` uses pyo3 but the `bin` is just a simple binary that doesn't link to `libpython`.

The bindings detection might need to be changed to be per-target, and allow users to override it in `targets` configuration:

```toml
[[tool.maturin.targets]]
name = "example"
kind = "bin"
bindings = "pyo3"  # example links to libpython

[[tool.maturin.targets]]
name = "example"
kind = "lib"
bindings = "cffi" # or pyo3 and others
```
