### ISSUE TITLE
"symbol __cxa_thread_atexit_impl, version GLIBC_2.18 not defined" running maturin 0.8.3 wheel in manylinux2014_aarch64

### ISSUE THREAD

**Issue by JEnoch** [PyO3/maturin#369]
Please provide the following information: 
 * Your python version (`python -V`): **3.8.6**
 * Your pip version (`pip -V`): **20.2.3**
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version? 
      **Yes: same issue with pip 20.2.4**
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): 
    **None, I just run** `maturin --help`
 * Does `cargo build` work? 
   **Not relevant**
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? 
   **Not on windows**

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:
  * I install maturin 0.8.3 in the latest [manylinux2014_aarch64 (sha256: 576ffd8ecbda)](https://quay.io/repository/pypa/manylinux2014_aarch64?tab=tags) and run `maturin --help` : 
   ```bash
   docker run --init -it --rm quay.io/pypa/manylinux2014_aarch64:latest /bin/bash -c "/opt/python/cp38-cp38/bin/pip install maturin && /opt/python/cp38-cp38/bin/maturin --version"
   ```
   The result output is:
   ```bash
   Collecting maturin
  Downloading maturin-0.8.3-py3-none-manylinux2014_aarch64.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 3.2 MB/s
Collecting toml~=0.10.0
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Installing collected packages: toml, maturin
Successfully installed maturin-0.8.3 toml-0.10.1
/opt/python/cp38-cp38/bin/maturin: relocation error: /opt/python/cp38-cp38/bin/maturin: symbol __cxa_thread_atexit_impl, version GLIBC_2.18 not defined in file libc.so.6 with link time reference
   ```

**Comment by JEnoch** [comment]
The issue looks similar to the one described in https://stackoverflow.com/questions/39744926/how-can-i-compile-a-rust-program-so-it-doesnt-use-cxa-thread-atexit-impl .
Which Rust toolchain was used to build the [maturin-0.8.3-py3-none-manylinux2014_aarch64.whl](https://files.pythonhosted.org/packages/fa/82/740d07dfd2f51949cde13cc2e4a25a13d17b1d317de5c5b8f357e2206634/maturin-0.8.3-py3-none-manylinux2014_aarch64.whl) ?

**Comment by JEnoch** [comment]
As a workaround, I created a Docker image based on manylinux2014_aarch64 and including a compiled version of maturin 0.8.3: https://hub.docker.com/repository/docker/adlinktech/manylinux2014-aarch64-rust-nightly
See its [Dockerfile](https://github.com/eclipse-zenoh/zenoh/blob/master/docker/manylinux2014-aarch64-rust-nightly/Dockerfile).

**Comment by konstin** [comment]
The aarch64 builder was building a wheel that was not actually manywheel compliant, as it was built with the glibc toolchain. If tried to fix this by building a musl binary as I already do for the other platforms, but now I'm getting errors when compiling dependencies (https://cloud.drone.io/PyO3/maturin/234/1/2), so publishing a fixed wheel is blocked on figuring out ci.

**Comment by JEnoch** [comment]
I was able to compile maturin 0.9.3-alpha.3 in a Docker python:3.8-buster image after installing the aarch64 musl toolchain and applying this workaround for rust-lang/compiler-builtins#201 issue: https://github.com/rust-lang/rust/issues/46651#issuecomment-433611633

Thus I think adding something like this to your .drone.yml commands should be good enough:
```bash
wget http://musl.cc/aarch64-linux-musl-cross.tgz
tar xzvf aarch64-linux-musl-cross.tgz -C /opt --strip-components=1
export PATH=$PATH:/opt/bin
echo '[target.aarch64-unknown-linux-musl]' >> ~/.cargo/config
echo 'linker = "aarch64-linux-musl-gcc"' >> ~/.cargo/config
echo 'rustflags = [ "-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc" ]' >> ~/.cargo/config
```

**Comment by konstin** [comment]
Unfortunately, this still fails at bzip-sys: https://cloud.drone.io/PyO3/maturin/270/1/2

Config:

```yml
- name: publish
  image: python:3.8-buster
  environment:
    PATH: "/root/.local/bin:/root/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    MATURIN_PASSWORD:
      from_secret: MATURIN_PASSWORD
  commands:
    # https://github.com/PyO3/maturin/issues/369#issuecomment-719615672
    - wget -q http://musl.cc/aarch64-linux-musl-cross.tgz
    - tar xzf aarch64-linux-musl-cross.tgz -C /opt --strip-components=1
    - export PATH=$PATH:/opt/bin
    - mkdir ~/.cargo
    - echo '[target.aarch64-unknown-linux-musl]' >> ~/.cargo/config
    - echo 'linker = "aarch64-linux-musl-gcc"' >> ~/.cargo/config
    - echo 'rustflags = [ "-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc" ]' >> ~/.cargo/config
    - curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal -y
    - rustup target add aarch64-unknown-linux-musl
    - cargo build --release --target aarch64-unknown-linux-musl
    - cargo run --release --target aarch64-unknown-linux-musl -- publish -u konstin -b bin --no-sdist --target aarch64-unknown-linux-musl
```
