### ISSUE TITLE
project-url fails when uploading to pypi

### ISSUE THREAD

**Issue by sbdchd** [PyO3/maturin#386]
I believe that the type for `project-url` shouldn't be a `Vec<str>` but instead a `HashMap<str, str>` since it's a dict in the docs:

https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls

This is the error I get when trying to upload a generated wheel to pypi:

```
Content received from server:
<html>
 <head>
  <title>400 Invalid value for project_urls. Error: Use both a label and an URL.</title>
 </head>
 <body>
  <h1>400 Invalid value for project_urls. Error: Use both a label and an URL.</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
Invalid value for project_urls. Error: Use both a label and an URL.


 </body>
</html>
HTTPError: 400 Client Error: Invalid value for project_urls. Error: Use both a label and an URL. for url: https://upload.pypi.org/legacy/
```

So I think instead of the `Cargo.toml` having

```toml
[package.metadata.maturin]
project-url = ["https://github.com/ghost/example"]
```

it should be

```toml
[package.metadata.maturin]
project-url = { homepage = "https://github.com/ghost/example" }
```
