### ISSUE TITLE
Docker and nightly

### ISSUE THREAD

**Issue by hwchen** [PyO3/maturin#413]
Please provide the following information: 
 * Your python version (`python -V`): docker image
 * Your pip version (`pip -V`): docker image
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): pyo3
 * Does `cargo build` work?
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

In github actions:
- install nightly toolchain with override = true
- `docker run ... konstin2/maturin build --release...`
get error:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
```

Does using the docker image support nightly? From the `Dockerfile` it looks like the image installs its own rustc and toolchain, so the separate install of the nightly toolchain is useless.

**Comment by konstin** [comment]
I've added some more information to the readme (https://github.com/PyO3/maturin/commit/9f95d0af69291ab0811380f92bcb971d0c96cba8#diff-1550ec65ac92f65817fc28928dfef526912b5f52356ff43651369bae92f56031). The problem is essentially that the image I can provide rather is really limited, so I've added instructions to build your own setup. Could you check if that works for you?

**Comment by hwchen** [comment]
Thanks, this is super helpful! I’ll try this out soon, the examples look pretty straightforward.

**Comment by hwchen** [comment]
Thanks again. I got the Github action to work, just wanted to leave some notes here in case anybody needs to also access private repos during the build:
```
 create_wheels_manylinux:
    name: Create wheels for manylinux
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - run: yum update && yum install -y openssh openssh-clients

      - uses: webfactory/ssh-agent@85353917a25aa1f197c5dff70d3ab6ef5aa88cd4
        with:
          ssh-private-key: ${{ secrets.SQLPARSER_PRIVATE_KEY }}

```
- I'm using `webfactory/ssh-agent`, its next release 0.5.0 will have support for docker workflows, I just referenced a commit here.
- You need to install ssh-agent.
- You need to use at least manylinux2014, earlier versions don't have the correct versions of libraries like `libc` that the `node` required by `webfactory/ssh-agent` can link against.
