### ISSUE TITLE
DLL load failed while importing

### ISSUE THREAD

**Issue by Stateford** [PyO3/maturin#466]
python: 3.9.2
pip: 20.2.3
pyo3: 0.13.2
windows 10

Hello,

I'm trying to build a wheel from a workspace. I am using one crate to generate a rlib and a cdylib, and another lib to consume the rlib. I'm getting the following error during build:

```
PS C:\Users\{USER}\github\rust\usb-concept\py-usblib> maturin build
🔗 Found pyo3 bindings
🐍 Found CPython 3.9 at C:\Users\{USER}\AppData\Local\Programs\Python\Python39\python.exe
⚠ There are local dependencies, which the source distribution might not include: usblib
````

when I try to import my python project I get the following error:

```
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import py_usblib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\{USER}\AppData\Local\Programs\Python\Python39\lib\site-packages\py_usblib\__init__.py", line 1, in <module>
    from .py_usblib import list_devices
ImportError: DLL load failed while importing py_usblib: The specified module could not be found.
```

I have tried to temporarily add the rust target path containing all project DLL's to the PATH, but python could still not find them. I cannot figure out what the issue is at this point

Here is my project layout

```
├───c_usblib     [c executable]
│   └───out
├───include
├───py-usblib    [pyo3 module]
│   └───src
│   └───py_usblib [python module -> from .py_usblib import *]
└───usblib          [cydlib + rlib]
    ├───src
```

I have also tried copying the DLL files to the site-packages and it still would not find it. I'm not sure what's wrong at this point, or what DLL it's complaining about.

**Comment by messense** [comment]
> ⚠ There are local dependencies, which the source distribution might not include: usblib

This warning only applies to sdist, shouldn't be a problem if you are installing the binary wheel.

Can you find `py_usblib.dll` in `C:\Users\{USER}\AppData\Local\Programs\Python\Python39\lib\site-packages\py_usblib`

**Comment by Stateford** [comment]
`py_usblib.dll`is missing from that directory, but there are these files.

```
|   py_usblib.cp39-win_amd64.pyd
|   __init__.py
```

I tried copying the DLL file to this directory, but it did not work properly. I also added the target directory to the PATH so the DLL will be exposed, but that also did not work.

**Comment by messense** [comment]
My bad, `py_usblib.cp39-win_amd64.pyd` looks ok.

Could paste some code? Like the function signature with `#[pymodule]` annotation.

**Comment by Stateford** [comment]
py-usblib/src/lib.rs
```rust
extern crate pyo3;
extern crate libusblib;

use pyo3::prelude::*;
use pyo3::wrap_pyfunction;


#[pyfunction]
fn list_devices() -> PyResult<()> {
    libusblib::list_devices().unwrap();
    Ok(())
}

#[pymodule]
fn py_usblib(py: Python, module: &PyModule) -> PyResult<()> {
    module.add_function(wrap_pyfunction!(list_devices, module)?)?;

    Ok(())
}
```

py-usblib/py_usblib/__init__.py
```py
from .py_usblib import list_devices

__all__ = [
    "list_devices"
]
```

py-usblib/cargo.toml
```toml
[package]
name = "py-usblib"
version = "0.1.0"
authors = ["name"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_usblib"
crate-type = ["cdylib"]

[dependencies]
usblib = { path = "../usblib"}

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
```
