### ISSUE TITLE
Provide a GitHub action template to build and publish to pypi using Maturin

### ISSUE THREAD

**Issue by Tpt** [PyO3/maturin#492]
It would be great to provide as part of Maturin documentation a template for a GitHub actions that builds wheels for as many targets as possible and publish them on Pypi. It would avoid new Maturin users like me to "reinvent the wheel" on this side.
Here if for example [my configuration for Oxigraph](https://github.com/oxigraph/oxigraph/blob/abc659565f699a7b0bf1664456a9d35d59c00279/.github/workflows/release.yml#L82).

**Comment by konstin** [comment]
That's definitely a good idea! It might also make sense to create a maturin github actions similar to [actions-rs/cargo](https://github.com/actions-rs/cargo). Either way, this example should get its own repository and should show how to test with pytest and how to publish for windows, linux (through manylinux) and mac

**Comment by messense** [comment]
I've put together a initial naive version: https://github.com/messense/maturin-action

It doesn't support using manylinux docker images at the moment but could be added later.

**Comment by konstin** [comment]
This works great, thank you!

I'm using this for an internal project where there is a main python project and an optional pure rust library in subdirectory, this is the config that I'm using:

```yaml
name: maturin

on: push

jobs:
  maturin:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions-rs/toolchain@v1
        id: rustup
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Cargo build
      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            html-py-ever/target
          key: html-py-ever-${{ runner.os }}-${{ steps.rustup.outputs.rustc_hash }}-${{ hashFiles('Cargo.lock') }}
      - uses: messense/maturin-action@v1
        with:
          command: build
          manylinux: 2_17
          args: --release --strip -m html-py-ever/Cargo.toml

      # Install python dependencies for main project
      - uses: actions/cache@v1
        id: poetry-cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install Poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1.1.4
        with:
          virtualenvs-in-project: true
      - run: poetry install
        if: steps.poetry-cache.outputs.cache-hit != 'true'
      - name: Install html-py-ever
        run: pip install html-py-ever --find-links html-py-ever/target/wheels/

      # Run tests
      - run: .venv/bin/pytest
 ```
