### ISSUE TITLE
Invalid wheel generated when using PEP 621 metadata

### ISSUE THREAD

**Issue by ethanhs** [PyO3/maturin#592]
Please provide the following information: 
 * Your python version (`python -V`): Python 3.9.5
 * Your pip version (`pip -V`): 21.1.1
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version? N/A
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): pyo3 (doesn't really matter)
 * Does `cargo build` work? N/A
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? N/A

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

Generate a wheel with the following in the `pyproject.toml`:

```
[project]
...
readme = "README.md"
requires-python = ">=3.7,<4"
license { file = "LICENSE" }
...
```

The above will inline the text of LICENSE in the METADATA of the generated wheel. However, it seems that maturin doesn't properly fold the headers (i.e. put a space on each new line) per RFC822 https://datatracker.ietf.org/doc/html/rfc822#section-3.1.1

This causes pkginfo to parse the metadata incorrectly, and causes `twine check` to fail.

An example repo where this happened: https://github.com/ethanhs/ryaml/ (specifically commit 1808286db1379d04b6069626cd149cf3cb02149d). I have worked around this by manually folding my LICENSE file...

**Comment by messense** [comment]
Thanks for reporting!

I am curious that since you are using a standard MIT license, why not just add `license = "MIT"` to `Cargo.toml`?

**Comment by messense** [comment]
Thanks for reporting!

I am curious that since you are using a standard MIT license, why not just add `license = "MIT"` to `Cargo.toml`?

**Comment by ethanhs** [comment]
Very reasonable question! I was reading through PEP 621 because I noticed that maturin supported it, and as far as I know, you can specify `license = { text = "..."  }` but I believe that is supposed to be the contents of the LICENSE file anyway?

**Comment by messense** [comment]
> and as far as I know, you can specify license = { text = "..." } but I believe that is supposed to be the contents of the LICENSE file anyway?

Yes. We do need to fix this issue.

**Comment by ethanhs** [comment]
Hm, though looking at what other things generate I do think PEP 621 should probably allow something like
```
license = {text = "MIT"}
```

so I'll ask for a clarification.

**Comment by messense** [comment]
Can you try #594 ? You can install it with `pip install https://github.com/messense/maturin/archive/refs/heads/fix-pep621-long-header.zip`

**Comment by ethanhs** [comment]
That seems to have made Twine happy! Thanks :)

**Comment by Alex-ley-scrub** [comment]
related to PEP 621 is the dynamic stuff, is there any plan to support it for dependencies and optional-dependencies?

e.g.
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata
https://peps.python.org/pep-0621/#dynamic

```toml
[project]
name = "my_package"
dynamic = ["version", "readme", "dependencies", "optional-dependencies"]

[tool.maturin.dynamic]
version = {attr = "my_package.__version__"}
readme = {file = "README.md"}
dependencies = {file = "requirements.txt"}

[tool.maturin.dynamic.optional-dependencies]
dev = {file = "requirements.dev.txt"}
test = {file = "requirements.dev.txt"}
```
