### ISSUE TITLE
Can't get python-source working

### ISSUE THREAD

**Issue by ShanWeera** [PyO3/maturin#606]
Hey guys. I know this feature is still in beta, but I really need this for what I'm trying to achieve.

**OS:** WIndows 10
**Python:** 3.8
**Maturin:**  0.11.3-beta.2

Cargo.toml:
```toml
[package]
name = "dima"

[lib]
crate-type = ["cdylib"]
name = "helpers"

[dependencies]
rand = "0.8.4"
linreg = "0.2.0"
maplit = "1.0.2"
reduce = "0.1.4"
bio = "0.37.0"
serde_json = "1.0.66"
serde = { version = "1.0", features = ["derive"] }
pyo3 = { version = "0.14.1", features = ["extension-module"] }

[package.metadata.maturin]
python-source = "source"
```

pyproject.toml (Using Poetry):
```toml
[tool.poetry]
name = "dima"
version = "0.1.0"

[project]
name = "dima"

[build-system]
requires = ["poetry-core>=1.0.0", "maturin>=0.11,<0.12"]
build-backend = "maturin"

[project.scripts]
dima-cli = "dima.bin._dima:main"
```

Directory Structure:
```
├── Cargo.lock
├── Cargo.toml
├── source
│   └── dima
│       ├── __init__.py
│       ├── bin
│       │   └── _dima.py
│       └── module.py
│   
└── src
    └── lib.rs
```

The issue is that none of the Python source files inside the `source` directory is copied over. Works fine with `lib.name`.

Is there anything obviously wrong in how I'm doing this?

**Comment by davidhewitt** [comment]
When "copied over", do you mean during an install, or when building a wheel, or some other time?

**Comment by messense** [comment]
Can you provide a list of commands to reproduce your issue?

**Comment by ShanWeera** [comment]
> When "copied over", do you mean during an install, or when building a wheel, or some other time?

Both. I've tried using `maturin develop --release` as well as building the wheel using `maturin build` and installing. Neither of it ends up copying the Python source files.

**Comment by messense** [comment]
```toml
[lib]
crate-type = ["cdylib"]
name = "helpers"
```

Why is `lib.name` called `helpers` while project and directory name called `dima`? And what do you expect after `maturin develop`/`maturin build`, what Python code did you run? Is there any Python import error?

It would be very helpful if you can create a public repository or zip archive containing the minimal code that can reproduce the issue.

**Comment by ShanWeera** [comment]
> ```toml
> [lib]
> crate-type = ["cdylib"]
> name = "helpers"
> ```
> 
> Why is `lib.name` called `helpers` while project and directory name called `dima`? And what do you expect after `maturin develop`/`maturin build`, what Python code did you run? Is there any Python import error?
> 
> It would be very helpful if you can create a public repository or zip archive containing the minimal code that can reproduce the issue.

What I'm trying to achieve is to do some heavy data-processing using Rust (hence the word "helpers"), and transform the results using Python (would like to do everything in Rust, but for some reasons I won't get into, we need to use Python for the transformation). You think the naming could be what's causing the issue?

**Comment by messense** [comment]
`lib.name` should match the Python module name if provided.

See https://github.com/PyO3/maturin#mixed-rustpython-projects

**Comment by messense** [comment]
If you want it to be a submodule `dima.helpers` you need to use `package.metadata.maturin.name`, for example 

```toml
[package.metadata.maturin] 
name = "dima.helpers" 
```

Here is a full example https://github.com/PyO3/maturin/tree/main/test-crates/pyo3-mixed-submodule
