### ISSUE TITLE
Invalid value for project-url when publishing

### ISSUE THREAD

**Issue by arturomf94** [PyO3/maturin#647]
* Python 3.9.6
 * pip 21.1.3
 * `cffi`
 * Does `cargo build` work? Yes
 
 Running something like this to publish on TestPYPI
 
 ```bash
docker run --rm -v $(pwd):/io konstin2/maturin publish -b cffi --no-sdist -r https://test.pypi.org/legacy/ -u USERNAME -p PASSWORD --skip-auditwheel --manylinux 2014
```
I get the following error:

```
Invalid value for project_urls. Error: Use both a label and an URL.
```

This is the relevant config I'm using: 

```toml
[package.metadata.maturin]
maintainer = "Pierre Tholoniat"
maintainer-email = "pierre@tholoniat.com"
requires-dist = ["numpy>=1", "cffi>=1", "pycparser>=2"]
requires-python=">=3.6"
project-url = { "Homepage" = "https://github.com/OpenMined/sycret" }
```
